### ISSUE TITLE
Wayne Wilson

### ISSUE THREAD

**Issue by wynwlsn86** [Sidgi/Dictionary#1]

**Comment by Sidgi** [comment]
![Screen Shot 2019-04-25 at 6 40 40 PM](https://user-images.githubusercontent.com/39839481/56773130-df3d6000-678a-11e9-8f70-117af86fa4a7.png)
![Screen Shot 2019-04-25 at 6 40 31 PM](https://user-images.githubusercontent.com/39839481/56773131-df3d6000-678a-11e9-8991-5ee6b5bdb5bd.png)
![Screen Shot 2019-04-25 at 6 39 17 PM](https://user-images.githubusercontent.com/39839481/56773132-df3d6000-678a-11e9-85ad-b3f7d1325b81.png)
![Screen Shot 2019-04-25 at 6 39 00 PM](https://user-images.githubusercontent.com/39839481/56773133-df3d6000-678a-11e9-9532-d53706625553.png)
![Screen Shot 2019-04-25 at 6 41 08 PM](https://user-images.githubusercontent.com/39839481/56773136-e2385080-678a-11e9-8eec-a5d2958c74a9.png)
